- hosts: all
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install Apache
    yum:
      name: httpd
      state: latest 

  - name: Start and Enable Apache
    systemd:
      name: httpd
      state: started
      enabled: yes

  - name: Download template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page290/cryptop.zip
      dest: /tmp/cryptop.zip
  
  - name: Install Unzip
    yum:
      name: unzip
      state: latest

  - name: Extract Template
    unarchive:
      src: /tmp/cryptop.zip
      dest: /tmp/
      remote_src: yes
  
  - name: Move Template file to /var/www/html
    shell: "mv /tmp/cryptop-html/* /var/www/html/"
    args:
      creates: /var/www/html/about.html